[project]
name = "volumectrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "comtypes>=1.4.10",
    "mediapipe>=0.10.21",
    "opencv-python>=4.11.0.86",
    "pycaw>=20240210",
]
